In [1]:
import numpy as np 

In [2]:
np.__version__


'1.26.4'

In [3]:
a = [1,2,3,4]
b = (1,2,3,4) 
c = "alkaif ansari"
d = {1:"alkaif",2:"riza"}

In [4]:
def printArray(x):
    print(f"Array : {x} Type : {type(x)}")

In [5]:
np.array(["alkaif","riza"])

array(['alkaif', 'riza'], dtype='<U6')

In [6]:
printArray(np.array(a))

Array : [1 2 3 4] Type : <class 'numpy.ndarray'>


In [7]:
printArray(np.array(b))

Array : [1 2 3 4] Type : <class 'numpy.ndarray'>


In [8]:
printArray(np.array(c))

Array : alkaif ansari Type : <class 'numpy.ndarray'>


In [9]:
printArray(np.array(d))

Array : {1: 'alkaif', 2: 'riza'} Type : <class 'numpy.ndarray'>


### np.array()
* #### converts any data type to numpy array
* #### has mainly five parameters
* #### data
* #### datatype - like float, int, uint
* #### copy - whether copy the or works on the same
* #### order - row order C, column order F
* #### subok
* #### ndim

### Data Types in Numpy
* #### np.int_ or int - default 32
* #### np.int8, np.int16, np.int64
* #### np.uint8, np.uint16, np.uint32, np.uint64
* #### np.float16, np.float32, np.float64 or np.float_ or float
* #### np.complex64, np.complex128 or np.complex
* #### bool or np.bool
* #### np.str_ - fixed length string
* #### np.unicode_ - fixed length unicode
* #### np.object_
* #### np.void

In [10]:
# data, datatype, copy, order, subok, ndim
np.array([1,2,3,4],dtype=float,copy=True,order="F",subok=False,ndmin=2)

array([[1., 2., 3., 4.]])

In [11]:
arr = np.arange(9)
printArray(arr)

Array : [0 1 2 3 4 5 6 7 8] Type : <class 'numpy.ndarray'>


In [12]:
np.array(arr,dtype=float,copy=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [13]:
arr1=np.array(arr,copy=False)
printArray(arr1)

Array : [0 1 2 3 4 5 6 7 8] Type : <class 'numpy.ndarray'>


In [14]:
arr1[2]=-1
arr

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8])

### Indexing 
* #### arrayName[index]

In [15]:
arr

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8])

In [16]:
random1 = np.random.randint(3)
random2 = np.random.randint(9)
print(random1," ",random2)
print(arr[random1]," ",arr[random2] )

2   4
-1   4


In [17]:
array2d = np.array([[1,2,3,4,5,6,7,8,9],[9,8,7,6,5,4,3,2,1],[0,0,0,0,0,0,0,0,0]],ndmin=2)
print(array2d)
print(random1,random2)
array2d[random1,random2]

[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]
 [0 0 0 0 0 0 0 0 0]]
2 4


0

In [18]:
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]]],ndmin=3)
print(array3d)

array3d[1,np.random.randint(3),np.random.randint(3)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[-1 -2 -3]
  [-4 -5 -6]
  [-7 -8 -9]]]


-4

### Slicing 
* #### ArrayName[sliceRange]
* #### ArrayName[start:end]

In [19]:
print(arr[:])
print(arr[:4]) # end is not include [,)
print(arr[4:])
print(arr[1:4])
print(arr[-4:-1])
arr[1:6:2]

[ 0  1 -1  3  4  5  6  7  8]
[ 0  1 -1  3]
[4 5 6 7 8]
[ 1 -1  3]
[5 6 7]


array([1, 3, 5])

### Double Colon
* #### Used to slice the array based on specific pattern or step
* #### Like 1,3,5,...
* #### Like 1,5,9,...

In [20]:
print(arr[::])
print(arr[1::3])
print(arr[1::-3])  # no element from start to -3 steps backward except one 

[ 0  1 -1  3  4  5  6  7  8]
[1 4 7]
[1]


In [21]:
print(arr[::-1])
print(arr[::-3])

[ 8  7  6  5  4  3 -1  1  0]
[ 8  5 -1]


### 2D Slicing
* #### ArrayName[row,start:end]

In [22]:
array2d[1,::-3]

array([1, 4, 7])

In [23]:
print(array2d)
array2d[0:3,0:3]

[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]
 [0 0 0 0 0 0 0 0 0]]


array([[1, 2, 3],
       [9, 8, 7],
       [0, 0, 0]])

### Data Type 
* #### Integer - i
* #### Unsigned Integer - u
* #### Float - f
* #### Complex - c
* #### Boolean - b
* #### String - S
* #### TimeDelta - m
* #### DateTime - M
* #### Object - O
* #### Unicode String - U
* #### Memory - V 

In [24]:
print(a)
print(np.array(a,dtype='U'))


[1, 2, 3, 4]
['1' '2' '3' '4']


In [25]:
# mixture conversion not allowed 
# l1 = ['a','b','1','2']
# np_Array = np.array(l1)
# np_Array.astype(int)


#### Shape 
* #### ArrayName.shape - to get the dimensions

In [26]:
array3d.shape

(2, 3, 3)

In [27]:
arr2 = np.array(np.arange(4),ndmin=5)
arr2.shape

(1, 1, 1, 1, 4)

### Reshape
* #### ArrayName.reshape(dimensions)
* #### ArrayName.reshape(x,y,z)

In [28]:
randomArray = np.random.randint(1,16,16)
len(randomArray)
randomArray2d=randomArray.reshape(4,4)
randomArray2d

array([[14,  9, 10,  3],
       [ 5,  8, 14,  2],
       [10,  9, 13,  5],
       [ 4,  1,  4, 11]])

### To flatten an n-dimension array to one dimension array
* #### ArrayName.reshape(-1)

In [29]:
print(randomArray2d.shape)
randomArray2d.reshape(-1)

(4, 4)


array([14,  9, 10,  3,  5,  8, 14,  2, 10,  9, 13,  5,  4,  1,  4, 11])

### nditer
* #### To iterate over complex array in less code
* #### for i in np.nditer(ArrayName):


In [30]:
print(array3d)
for i in np.nditer(array3d[0,:,::2]):
    print(i)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[-1 -2 -3]
  [-4 -5 -6]
  [-7 -8 -9]]]
1
3
4
6
7
9
